# Default initial positions for d1_550_description's ros2_control fake system

initial_positions:
  Joint1: 0
  Joint2: -1.57
  Joint3: 1.57
  Joint4: 0
  Joint5: 0
  Joint6: 0
  Joint_L: 0
  Joint_R: 0