float64 pick_x
float64 pick_y
float64 pick_z
string shape
float64 dimension_x
float64 dimension_y
float64 dimension_z
float64 rot_x
float64 rot_y
float64 rot_z
string pick_grasp
---
bool    success
string  message